# Generated by Django 4.2.8 on 2023-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'enlace', 'verbose_name_plural': 'enlaces'},
        ),
        migrations.AddField(
            model_name='link',
            name='key',
            field=models.SlugField(default=2, max_length=100, unique=True, verbose_name='Nombre clave'),
            preserve_default=False,
        ),
    ]
